/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author migyu
 */
public class MainFrame extends javax.swing.JFrame {
    String numTemp = "";
    String numResult = "";
    String operator = "";
    double inputTemp = 0;
    double inputResult = 0;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setTitle("공학용 계산기");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btnCE = new javax.swing.JButton();
        resultField = new javax.swing.JTextField();
        btnC = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        btnSta = new javax.swing.JButton();
        btnPM = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        btnNot = new javax.swing.JButton();
        Sta22 = new javax.swing.JButton();
        btnXor = new javax.swing.JButton();
        Sta24 = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnAnd = new javax.swing.JButton();
        Sta28 = new javax.swing.JButton();
        btnComma = new javax.swing.JButton();
        Sta30 = new javax.swing.JButton();
        Sta31 = new javax.swing.JButton();
        Sta32 = new javax.swing.JButton();
        BtnOne = new javax.swing.JButton();
        BtnThree = new javax.swing.JButton();
        BtnTwo = new javax.swing.JButton();
        Sta36 = new javax.swing.JButton();
        Sta37 = new javax.swing.JButton();
        Sta38 = new javax.swing.JButton();
        Sta39 = new javax.swing.JButton();
        Sta40 = new javax.swing.JButton();
        Sta41 = new javax.swing.JButton();
        Sta42 = new javax.swing.JButton();
        Sta43 = new javax.swing.JButton();
        Sta44 = new javax.swing.JButton();
        Sta45 = new javax.swing.JButton();
        Sta46 = new javax.swing.JButton();
        Sta47 = new javax.swing.JButton();
        Sta48 = new javax.swing.JButton();
        Sta49 = new javax.swing.JButton();
        Sta50 = new javax.swing.JButton();
        Sta51 = new javax.swing.JButton();
        Sta52 = new javax.swing.JButton();
        Sta53 = new javax.swing.JButton();
        Sta54 = new javax.swing.JButton();
        Sta55 = new javax.swing.JButton();
        Sta56 = new javax.swing.JButton();
        Sta57 = new javax.swing.JButton();
        Sta58 = new javax.swing.JButton();
        Sta59 = new javax.swing.JButton();
        btnInt = new javax.swing.JButton();
        btnResult = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(227, 221, 211));

        jRadioButton1.setText("Hex");

        jRadioButton2.setText("Dec");

        jRadioButton3.setText("Oct");

        jRadioButton4.setText("Bin");

        btnCE.setBackground(new java.awt.Color(235, 233, 230));
        btnCE.setForeground(new java.awt.Color(255, 0, 51));
        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        resultField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultFieldActionPerformed(evt);
            }
        });

        btnC.setBackground(new java.awt.Color(235, 233, 230));
        btnC.setForeground(new java.awt.Color(255, 0, 51));
        btnC.setText("C");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnBackspace.setBackground(new java.awt.Color(235, 233, 230));
        btnBackspace.setForeground(new java.awt.Color(255, 0, 51));
        btnBackspace.setText("Backspace");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        jRadioButton5.setText("Degrees");

        jRadioButton6.setText("Grads");

        jRadioButton7.setText("Radians");

        btnSta.setBackground(new java.awt.Color(235, 233, 230));
        btnSta.setText("Sta");
        btnSta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaActionPerformed(evt);
            }
        });

        btnPM.setBackground(new java.awt.Color(235, 233, 230));
        btnPM.setForeground(new java.awt.Color(51, 51, 255));
        btnPM.setText("+/-");
        btnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(235, 233, 230));
        btn0.setForeground(new java.awt.Color(51, 51, 255));
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(235, 233, 230));
        btn1.setForeground(new java.awt.Color(51, 51, 255));
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(235, 233, 230));
        btn3.setForeground(new java.awt.Color(51, 51, 255));
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(235, 233, 230));
        btn2.setForeground(new java.awt.Color(51, 51, 255));
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(235, 233, 230));
        btn6.setForeground(new java.awt.Color(51, 51, 255));
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(235, 233, 230));
        btn5.setForeground(new java.awt.Color(51, 51, 255));
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(235, 233, 230));
        btn4.setForeground(new java.awt.Color(51, 51, 255));
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(235, 233, 230));
        btn7.setForeground(new java.awt.Color(51, 51, 255));
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(235, 233, 230));
        btn9.setForeground(new java.awt.Color(51, 51, 255));
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(235, 233, 230));
        btn8.setForeground(new java.awt.Color(51, 51, 255));
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnPlus.setBackground(new java.awt.Color(235, 233, 230));
        btnPlus.setForeground(new java.awt.Color(255, 0, 0));
        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMin.setBackground(new java.awt.Color(235, 233, 230));
        btnMin.setForeground(new java.awt.Color(255, 0, 0));
        btnMin.setText("-");
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });

        btnNot.setBackground(new java.awt.Color(235, 233, 230));
        btnNot.setForeground(new java.awt.Color(255, 0, 0));
        btnNot.setText("Not");
        btnNot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotActionPerformed(evt);
            }
        });

        Sta22.setBackground(new java.awt.Color(235, 233, 230));
        Sta22.setForeground(new java.awt.Color(255, 0, 0));
        Sta22.setText("2");
        Sta22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta22ActionPerformed(evt);
            }
        });

        btnXor.setBackground(new java.awt.Color(235, 233, 230));
        btnXor.setForeground(new java.awt.Color(255, 0, 0));
        btnXor.setText("Xor");
        btnXor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXorActionPerformed(evt);
            }
        });

        Sta24.setBackground(new java.awt.Color(235, 233, 230));
        Sta24.setForeground(new java.awt.Color(255, 0, 0));
        Sta24.setText("5");
        Sta24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta24ActionPerformed(evt);
            }
        });

        btnMul.setBackground(new java.awt.Color(235, 233, 230));
        btnMul.setForeground(new java.awt.Color(255, 0, 0));
        btnMul.setText("*");
        btnMul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMulActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(235, 233, 230));
        btnDiv.setForeground(new java.awt.Color(255, 0, 0));
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnAnd.setBackground(new java.awt.Color(235, 233, 230));
        btnAnd.setForeground(new java.awt.Color(255, 0, 0));
        btnAnd.setText("And");
        btnAnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndActionPerformed(evt);
            }
        });

        Sta28.setBackground(new java.awt.Color(235, 233, 230));
        Sta28.setForeground(new java.awt.Color(255, 0, 0));
        Sta28.setText("Mod");
        Sta28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta28ActionPerformed(evt);
            }
        });

        btnComma.setBackground(new java.awt.Color(235, 233, 230));
        btnComma.setForeground(new java.awt.Color(51, 51, 255));
        btnComma.setText(".");
        btnComma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommaActionPerformed(evt);
            }
        });

        Sta30.setForeground(new java.awt.Color(153, 153, 153));
        Sta30.setText("D");
        Sta30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta30ActionPerformed(evt);
            }
        });

        Sta31.setForeground(new java.awt.Color(153, 153, 153));
        Sta31.setText("F");
        Sta31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta31ActionPerformed(evt);
            }
        });

        Sta32.setForeground(new java.awt.Color(153, 153, 153));
        Sta32.setText("E");
        Sta32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta32ActionPerformed(evt);
            }
        });

        BtnOne.setForeground(new java.awt.Color(153, 153, 153));
        BtnOne.setText("A");
        BtnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOneActionPerformed(evt);
            }
        });

        BtnThree.setForeground(new java.awt.Color(153, 153, 153));
        BtnThree.setText("C");
        BtnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThreeActionPerformed(evt);
            }
        });

        BtnTwo.setForeground(new java.awt.Color(153, 153, 153));
        BtnTwo.setText("B");
        BtnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTwoActionPerformed(evt);
            }
        });

        Sta36.setBackground(new java.awt.Color(235, 233, 230));
        Sta36.setForeground(new java.awt.Color(255, 51, 255));
        Sta36.setText("x^3");
        Sta36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta36ActionPerformed(evt);
            }
        });

        Sta37.setBackground(new java.awt.Color(235, 233, 230));
        Sta37.setForeground(new java.awt.Color(255, 51, 255));
        Sta37.setText("cos");
        Sta37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta37ActionPerformed(evt);
            }
        });

        Sta38.setBackground(new java.awt.Color(235, 233, 230));
        Sta38.setForeground(new java.awt.Color(255, 51, 255));
        Sta38.setText("sin");
        Sta38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta38ActionPerformed(evt);
            }
        });

        Sta39.setBackground(new java.awt.Color(235, 233, 230));
        Sta39.setForeground(new java.awt.Color(255, 51, 255));
        Sta39.setText("log");
        Sta39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta39ActionPerformed(evt);
            }
        });

        Sta40.setBackground(new java.awt.Color(235, 233, 230));
        Sta40.setForeground(new java.awt.Color(255, 51, 255));
        Sta40.setText("x^y");
        Sta40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta40ActionPerformed(evt);
            }
        });

        Sta41.setBackground(new java.awt.Color(235, 233, 230));
        Sta41.setForeground(new java.awt.Color(255, 51, 255));
        Sta41.setText("In");
        Sta41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta41ActionPerformed(evt);
            }
        });

        Sta42.setBackground(new java.awt.Color(235, 233, 230));
        Sta42.setForeground(new java.awt.Color(255, 51, 255));
        Sta42.setText("Exp");
        Sta42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta42ActionPerformed(evt);
            }
        });

        Sta43.setBackground(new java.awt.Color(235, 233, 230));
        Sta43.setForeground(new java.awt.Color(255, 51, 255));
        Sta43.setText("dms");
        Sta43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta43ActionPerformed(evt);
            }
        });

        Sta44.setBackground(new java.awt.Color(235, 233, 230));
        Sta44.setForeground(new java.awt.Color(255, 51, 255));
        Sta44.setText("F-E");
        Sta44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta44ActionPerformed(evt);
            }
        });

        Sta45.setBackground(new java.awt.Color(235, 233, 230));
        Sta45.setForeground(new java.awt.Color(255, 51, 255));
        Sta45.setText(")");
        Sta45.setToolTipText("");
        Sta45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta45ActionPerformed(evt);
            }
        });

        Sta46.setBackground(new java.awt.Color(235, 233, 230));
        Sta46.setForeground(new java.awt.Color(255, 51, 255));
        Sta46.setText("(");
        Sta46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta46ActionPerformed(evt);
            }
        });

        Sta47.setBackground(new java.awt.Color(235, 233, 230));
        Sta47.setForeground(new java.awt.Color(255, 51, 255));
        Sta47.setText("n!");
        Sta47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta47ActionPerformed(evt);
            }
        });

        Sta48.setBackground(new java.awt.Color(235, 233, 230));
        Sta48.setForeground(new java.awt.Color(255, 51, 255));
        Sta48.setText("tan");
        Sta48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta48ActionPerformed(evt);
            }
        });

        Sta49.setBackground(new java.awt.Color(235, 233, 230));
        Sta49.setForeground(new java.awt.Color(255, 51, 255));
        Sta49.setText("1/x");
        Sta49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta49ActionPerformed(evt);
            }
        });

        Sta50.setBackground(new java.awt.Color(235, 233, 230));
        Sta50.setForeground(new java.awt.Color(255, 51, 255));
        Sta50.setText("x^2");
        Sta50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta50ActionPerformed(evt);
            }
        });

        Sta51.setBackground(new java.awt.Color(235, 233, 230));
        Sta51.setForeground(new java.awt.Color(255, 0, 0));
        Sta51.setText("M+");
        Sta51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta51ActionPerformed(evt);
            }
        });

        Sta52.setBackground(new java.awt.Color(235, 233, 230));
        Sta52.setForeground(new java.awt.Color(0, 51, 255));
        Sta52.setText("pi");
        Sta52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta52ActionPerformed(evt);
            }
        });

        Sta53.setBackground(new java.awt.Color(235, 233, 230));
        Sta53.setForeground(new java.awt.Color(255, 0, 0));
        Sta53.setText("MS");
        Sta53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta53ActionPerformed(evt);
            }
        });

        Sta54.setBackground(new java.awt.Color(235, 233, 230));
        Sta54.setForeground(new java.awt.Color(255, 0, 0));
        Sta54.setText("MC");
        Sta54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta54ActionPerformed(evt);
            }
        });

        Sta55.setBackground(new java.awt.Color(235, 233, 230));
        Sta55.setForeground(new java.awt.Color(255, 0, 0));
        Sta55.setText("MR");
        Sta55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta55ActionPerformed(evt);
            }
        });

        Sta56.setForeground(new java.awt.Color(153, 153, 153));
        Sta56.setText("Dat");
        Sta56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta56ActionPerformed(evt);
            }
        });

        Sta57.setForeground(new java.awt.Color(153, 153, 153));
        Sta57.setText("s");
        Sta57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta57ActionPerformed(evt);
            }
        });

        Sta58.setForeground(new java.awt.Color(153, 153, 153));
        Sta58.setText("Sum");
        Sta58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta58ActionPerformed(evt);
            }
        });

        Sta59.setForeground(new java.awt.Color(153, 153, 153));
        Sta59.setText("Ave");
        Sta59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sta59ActionPerformed(evt);
            }
        });

        btnInt.setBackground(new java.awt.Color(235, 233, 230));
        btnInt.setForeground(new java.awt.Color(255, 0, 0));
        btnInt.setText("Int");
        btnInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntActionPerformed(evt);
            }
        });

        btnResult.setBackground(new java.awt.Color(235, 233, 230));
        btnResult.setForeground(new java.awt.Color(255, 0, 0));
        btnResult.setText("=");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Inv");

        jCheckBox2.setText("Hyp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Sta56, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Sta59, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta57, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta58, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSta, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Sta48, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(Sta50, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(Sta49, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Sta37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sta38, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sta43, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sta44, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Sta46, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(Sta45, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Sta42, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(Sta41, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Sta40, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(Sta39, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Sta36, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(Sta47, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Sta55, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta54, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta53, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Sta52, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta51, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(BtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(BtnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(BtnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(Sta30, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(Sta32, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(25, 25, 25)
                                    .addComponent(Sta31, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnComma, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGap(25, 25, 25)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Sta24, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Sta28, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnXor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnAnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(25, 25, 25)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(Sta22, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btnNot, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(25, 25, 25)
                                                    .addComponent(btnInt, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jRadioButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jRadioButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(resultField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton3)
                                    .addComponent(jRadioButton2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox1)
                                    .addComponent(jCheckBox2)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton7)
                                    .addComponent(jRadioButton6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sta59, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sta58, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Sta57, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Sta56, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnPM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnAnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sta28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnMul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sta24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnXor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnNot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Sta22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnComma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnInt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnResult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BtnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BtnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Sta31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sta30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sta45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sta43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sta39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sta37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Sta49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Sta48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sta54, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sta55, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sta53, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Sta51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Sta52, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private double calculate(String inputText) {
        
    }
    
    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnStaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStaActionPerformed

    private void btnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPMActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        numTemp += 0;
        resultField.setText(numTemp);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        numTemp += 1;
        resultField.setText(numTemp);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        numTemp += 3;
        resultField.setText(numTemp);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        numTemp += 2; resultField.setText(numTemp);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        numTemp += 6; resultField.setText(numTemp);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        numTemp += 5; resultField.setText(numTemp);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        numTemp += 4; resultField.setText(numTemp);
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        numTemp += 7; resultField.setText(numTemp);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        numTemp += 9; resultField.setText(numTemp);
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        numTemp += 8; resultField.setText(numTemp);

    }//GEN-LAST:event_btn8ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        inputTemp = Double.valueOf(numTemp);
        
        if(inputResult == 0){
            inputResult = inputTemp;
        } else {
            inputResult += inputTemp;
            
            numResult = String.valueOf(inputResult);
            resultField.setText(numResult);
            
            inputTemp = 0;
            numResult = "";
            operator = "+";
        }                                                                                                                                                                                                                                                                                                                                                                                                                                                    
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        if(inputResult == 0){
            inputResult = inputTemp;
        } else {
            inputResult -= inputTemp;
            
            numResult = String.valueOf(inputResult);
            resultField.setText(numResult);
            
            inputTemp = 0;
            numResult = "";
            operator = "-";
        }
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotActionPerformed

    private void Sta22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta22ActionPerformed

    private void btnXorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXorActionPerformed

    private void Sta24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta24ActionPerformed

    private void btnMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMulActionPerformed
        if(inputResult == 0){
            inputResult = inputTemp;
        } else {
            inputResult *= inputTemp;
            
            numResult = String.valueOf(inputResult);
            resultField.setText(numResult);
            
            inputTemp = 0;
            numResult = "";
            operator = "*";
        }      
    }//GEN-LAST:event_btnMulActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        if(inputResult == 0){
            inputResult = inputTemp;
        } else {
            inputResult /= inputTemp;
            
            numResult = String.valueOf(inputResult);
            resultField.setText(numResult);
            
            inputTemp = 0;
            numResult = "";
            operator = "/";
        }      
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnAndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAndActionPerformed

    private void Sta28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta28ActionPerformed

    private void btnCommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommaActionPerformed

    private void Sta30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta30ActionPerformed

    private void Sta31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta31ActionPerformed

    private void Sta32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta32ActionPerformed

    private void BtnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnOneActionPerformed

    private void BtnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnThreeActionPerformed

    private void BtnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTwoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTwoActionPerformed

    private void Sta36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta36ActionPerformed

    private void Sta37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta37ActionPerformed

    private void Sta38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta38ActionPerformed

    private void Sta39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta39ActionPerformed

    private void Sta40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta40ActionPerformed

    private void Sta41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta41ActionPerformed

    private void Sta42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta42ActionPerformed

    private void Sta43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta43ActionPerformed

    private void Sta44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta44ActionPerformed

    private void Sta45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta45ActionPerformed

    private void Sta46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta46ActionPerformed

    private void Sta47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta47ActionPerformed

    private void Sta48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta48ActionPerformed

    private void Sta49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta49ActionPerformed

    private void Sta50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta50ActionPerformed

    private void Sta51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta51ActionPerformed

    private void Sta52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta52ActionPerformed

    private void Sta53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta53ActionPerformed

    private void Sta54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta54ActionPerformed

    private void Sta55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta55ActionPerformed

    private void Sta56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta56ActionPerformed

    private void Sta57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta57ActionPerformed

    private void Sta58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta58ActionPerformed

    private void Sta59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sta59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sta59ActionPerformed

    private void btnIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIntActionPerformed

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        inputTemp = Double.valueOf(numTemp);
        
        switch (operator) {
            case "+":
                inputResult += inputTemp;
                break;
            case "-":
                inputResult -= inputTemp;
                break;
            case "*":
                inputResult *= inputTemp;
                break;
            case "/":
                inputResult /= inputTemp;
                break;
 
        }
    }//GEN-LAST:event_btnResultActionPerformed

    private void resultFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOne;
    private javax.swing.JButton BtnThree;
    private javax.swing.JButton BtnTwo;
    private javax.swing.JButton Sta22;
    private javax.swing.JButton Sta24;
    private javax.swing.JButton Sta28;
    private javax.swing.JButton Sta30;
    private javax.swing.JButton Sta31;
    private javax.swing.JButton Sta32;
    private javax.swing.JButton Sta36;
    private javax.swing.JButton Sta37;
    private javax.swing.JButton Sta38;
    private javax.swing.JButton Sta39;
    private javax.swing.JButton Sta40;
    private javax.swing.JButton Sta41;
    private javax.swing.JButton Sta42;
    private javax.swing.JButton Sta43;
    private javax.swing.JButton Sta44;
    private javax.swing.JButton Sta45;
    private javax.swing.JButton Sta46;
    private javax.swing.JButton Sta47;
    private javax.swing.JButton Sta48;
    private javax.swing.JButton Sta49;
    private javax.swing.JButton Sta50;
    private javax.swing.JButton Sta51;
    private javax.swing.JButton Sta52;
    private javax.swing.JButton Sta53;
    private javax.swing.JButton Sta54;
    private javax.swing.JButton Sta55;
    private javax.swing.JButton Sta56;
    private javax.swing.JButton Sta57;
    private javax.swing.JButton Sta58;
    private javax.swing.JButton Sta59;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAnd;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnComma;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnInt;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnNot;
    private javax.swing.JButton btnPM;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnResult;
    private javax.swing.JButton btnSta;
    private javax.swing.JButton btnXor;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JTextField resultField;
    // End of variables declaration//GEN-END:variables
}
